version: '2.0'
services:
  

  nginx:
    build: deps/nginx/
    image: thanhpk/nginx:assetup_2
    ports:
      - "2108:80"

    volumes:
      - /var/log:/var/log
      - /tmp/assets:/srv/assetup/assets

    links:
      - fpm

  fpm:
    build: .
    image: thanhpk/assetup:0.0.2
    volumes:
      - /tmp/assets:/srv/assetup/assets

    
