version: '2'
services:
    PROD.fpm: {image: 'thanhpk/assetup-fpm:0.1', volumes: ['/tmp/assets:/srv/assetup/assets'], ports: [], build: {context: /home/thanh/workspace/assetup}}
    PROD.NGINX.nginx: {links: ['PROD.fpm:fpm']}

