version: '2'
services:
    PROD.fpm: {build: {context: /home/thanh/workspace/assetup}, image: 'thanhpk/assetup-fpm:0.1', volumes: ['/tmp/assets:/srv/assetup/assets', './src:/srv/assetup'], ports: []}
    PROD.NGINX.nginx: {image: 'thanhpk/assetup-nginx:0.1', volumes: ['/var/log:/var/log', '/tmp/assets:/srv/assetup/assets'], links: ['PROD.fpm:fpm'], ports: ['2108:80']}

