version: '2'
services:
    PROD.nginx: {image: 'thanhpk/assetup-nginx:0.1', volumes: ['/var/log:/var/log', '/tmp/assets:/srv/assetup/assets'], ports: [], build: {context: /home/thanh/workspace/assetup/deps/nginx}}

